# Generated by Django 4.2 on 2023-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='noches',
            field=models.IntegerField(default=1),
        ),
    ]
