# Generated by Django 4.2 on 2023-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_reservacion_noches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='tipo_cuarto',
            field=models.CharField(choices=[('S', 'Sencilla'), ('D', 'Doble'), ('U', 'Suite')], max_length=10),
        ),
    ]
